---

- name: add user {{ user.name }}
  user:
    name: "{{ user.name }}"
    password: "{{ user.pass | password_hash('sha512') }}"
    update_password: on_create

- name: setup home directory for user {{ user.name }}
  become: yes
  become_user: "{{ user.name }}"
  file:
    path: "{{ user_home }}/{{ dir_name }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0755"
  loop_control:
    loop_var: dir_name
  loop:
    - src
    - bin
    - pkg

- name: setup user profile {{ user_home }}/{{ user_profile }}
  become: yes
  become_user: "{{ user.name }}"
  file:
    path: "{{ user_home }}/{{ user_profile }}"
    state: touch
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0644"
    modification_time: preserve
    access_time: preserve

- name: include {{ user_profile }} into {{ user_home }}/.bashrc
  become: yes
  become_user: "{{ user.name }}"
  blockinfile:
    path: "{{ user_home }}/.bashrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK user_setup/{{ role_name }}"
    block: |
      source {{ user_home }}/{{ user_profile }}
