---
- name: install zsh
  package:
    name: zsh
    state: present

- name: install git for zsh config setup
  package:
    name: git
    state: present

- name: get zsh config installer in {{ user_home }}
  become: yes
  become_user: "{{ user.name }}"
  get_url:
    url: https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: "{{ user_home }}/.oh-my-zsh-installer.sh"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0755'

- name: setup zsh config for {{ user.name }}
  become: yes
  become_user: "{{ user.name }}"
  shell:
    cmd: "{{ user_home }}/.oh-my-zsh-installer.sh --unattended"
    chdir: "{{ user_home }}"
    creates: "{{ user_home }}/.oh-my-zsh"

- name: setup {{ user.name }}'s login shell
  user:
    name: "{{ user.name }}"
    shell: /bin/zsh
