---
- name: install requirements for zsh
  package:
    name:
      - zsh
      - git
    state: present

- name: get zsh config installer in {{ user_home }}
  become: yes
  become_user: "{{ user.name }}"
  get_url:
    url: https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: "{{ user_home }}/.oh-my-zsh-installer.sh"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0755'
  tags: network

- name: setup zsh config for {{ user.name }}
  become: yes
  become_user: "{{ user.name }}"
  shell:
    cmd: "{{ user_home }}/.oh-my-zsh-installer.sh --unattended"
    chdir: "{{ user_home }}"
    creates: "{{ user_home }}/.oh-my-zsh"
  tags: network

- name: include {{ user_profile }} into {{ user_home }}/.zshrc
  become: yes
  become_user: "{{ user.name }}"
  blockinfile:
    path: "{{ user_home }}/.zshrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK user_setup/{{ role_name }}"
    block: |
      source {{ user_home }}/{{ user_profile }}

- name: setup {{ user.name }}'s login shell
  user:
    name: "{{ user.name }}"
    shell: /bin/zsh
