---
- name: install requirements for gvm
  package:
    name:
      - curl
      - bison
    state: present

- name: get gvm installer under {{ user_home }}
  become: yes
  become_user: "{{ user.name }}"
  get_url:
    url: https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer
    dest: "{{ user_home }}/.gvm-installer.sh"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0755"
  tags: network

- name: install gvm for {{ user.name }}
  become: yes
  become_user: "{{ user.name }}"
  shell:
    cmd: "GVM_NO_UPDATE_PROFILE=YES {{ user_home }}/.gvm-installer.sh"
    chdir: "{{ user_home }}"
    creates: "{{ user_home }}/.gvm"
  tags: network

- name: setup go env for {{ user.name }}
  become: yes
  become_user: "{{ user.name }}"
  blockinfile:
    path: "{{ user_home }}/{{ user_profile }}"
    block: |
      [[ -s "${HOME}/.gvm/scripts/gvm" ]] && source "${HOME}/.gvm/scripts/gvm"
      export GOPATH="${HOME}" && export GOPROXY="https://goproxy.io" && export GO111MODULE="auto"
