---
- name: install requirements for tmux
  package:
    name:
      - tmux
      - perl
      - sed
      - git
      - xsel
      - xclip
    state: present

- name: pull tmux config in {{ user.name }}
  become: yes
  become_user: "{{ user.name }}"
  git:
    repo: 'https://github.com/gpakosz/.tmux.git'
    dest: "{{ user_home }}/.tmux"
    update: no
  tags: network

- name: setup tmux config for {{ user.name }}
  become: yes
  become_user: "{{ user.name }}"
  file:
    state: link
    src: "{{ user_home }}/.tmux/.tmux.conf"
    path: "{{ user_home }}/.tmux.conf"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
  tags: network

- name: prepare for tmux config custom by {{ user.name }}
  become: yes
  become_user: "{{ user.name }}"
  copy:
    remote_src: yes
    src: "{{ user_home }}/.tmux/.tmux.conf.local"
    dest: "{{ user_home }}/.tmux.conf.local"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
  tags: network

- name: custom tmux config for {{ user.name }}
  become: yes
  become_user: "{{ user.name }}"
  blockinfile:
    path: "{{ user_home }}/.tmux.conf.local"
    block: |
      set -gu prefix2
      unbind C-a
      unbind C-b
      set -g prefix C-s
      bind C-s send-prefix
      tmux_conf_copy_to_os_clipboard=true
      tmux_conf_new_pane_reconnect_ssh=true
      tmux_conf_theme_highlight_focused_pane=true
  tags: network
