---
- name: install tmux
  package:
    name: tmux
    state: present

- name: install perl for tmux config setup
  package:
    name: perl
    state: present

- name: install sed for tmux config setup
  package:
    name: sed
    state: present

- name: install git for tmux config setup
  package:
    name: git
    state: present

- name: pull tmux config in {{ user.name }}
  become: yes
  become_user: "{{ user.name }}"
  git:
    repo: 'https://github.com/gpakosz/.tmux.git'
    dest: "{{ user_home }}/.tmux"
    update: no

- name: setup tmux config for {{ user.name }}
  become: yes
  become_user: "{{ user.name }}"
  file:
    state: link
    src: "{{ user_home }}/.tmux/.tmux.conf"
    path: "{{ user_home }}/.tmux.conf"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"

- name: prepare for tmux config custom by {{ user.name }}
  become: yes
  become_user: "{{ user.name }}"
  copy:
    remote_src: yes
    src: "{{ user_home }}/.tmux/.tmux.conf.local"
    dest: "{{ user_home }}/.tmux.conf.local"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"

- name: custom tmux config for {{ user.name }}
  become: yes
  become_user: "{{ user.name }}"
  blockinfile:
    path: "{{ user_home }}/.tmux.conf.local"
    block: |
      set -gu prefix2
      unbind C-a
      unbind C-b
      set -g prefix C-s
      bind C-s send-prefix
