---

- name: install tsocks and connect-proxy
  package:
    name:
      - tsocks
      - connect-proxy
    state: present

- name: setup client
  include_tasks:
    file: each_proxy_server.yml
  loop: "{{ groups['servers'] }}"
  loop_control:
    loop_var: server_name
