VERSION = 1.6.x

.PHONY: build
build:
	ln -sf $(shell pwd)/accelerator.properties ~/.config/freeplane/$(VERSION)/accelerator.properties
	ln -sf $(shell pwd)/linux.freeplaneoptions ~/.config/freeplane/$(VERSION)/linux.freeplaneoptions
	ln -sf $(shell pwd)/mytemplates.mm ~/.config/freeplane/$(VERSION)/templates/mytemplates.mm
