VERSION = 1.6.x

.PHONY: build
build:
	ln -sf $(shell pwd)/accelerator.properties ~/.config/freeplane/$(VERSION)/accelerator.properties
	ln -sf $(shell pwd)/freeplaneoptions.linux ~/.config/freeplane/$(VERSION)/freeplaneoptions.linux
	ln -sf $(shell pwd)/mytemplates.mm ~/.config/freeplane/$(VERSION)/templates/mytemplates.mm
