---

- name: add user {{ user.name }}
  user:
    name: "{{ user.name }}"
    password: "{{ user.pass | password_hash('sha512') }}"
    update_password: on_create
    append: yes
    groups: [docker]

- name: setup /home/{{ user.name }}/src directory
  file:
    path: "/home/{{ user.name }}/src"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0755"

- name: setup /home/{{ user.name }}/bin directory
  file:
    path: "/home/{{ user.name }}/bin"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0755"

- name: setup /home/{{ user.name }}/pkg directory
  file:
    path: "/home/{{ user.name }}/pkg"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0755"
