---

- name: add user {{ user.name }}
  user:
    name: "{{ user.name }}"
    password: "{{ user.pass | password_hash('sha512') }}"
    update_password: on_create
    append: yes
    groups: [docker]

- name: setup {{ user_home }}/src directory
  become: yes
  become_user: "{{ user.name }}"
  file:
    path: "{{ user_home }}/src"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0755"

- name: setup {{ user_home }}/bin directory
  become: yes
  become_user: "{{ user.name }}"
  file:
    path: "{{ user_home }}/bin"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0755"

- name: setup {{ user_home }}/pkg directory
  become: yes
  become_user: "{{ user.name }}"
  file:
    path: "{{ user_home }}/pkg"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0755"
